name: smart_bike_tracker
description: "Smart Bike Tracker - Anti-theft tracking system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  
  # BLE Communication
  flutter_blue_plus: ^1.32.12
  
  # Permissions (needed for BLE scanning)
  permission_handler: ^11.3.1
  
  # Local Storage (for auto-connect)
  shared_preferences: ^2.3.3
  
  # Location Services (for GPS tracking)
  geolocator: ^13.0.2
  
  # Geocoding (for country detection from coordinates)
  geocoding: ^3.0.0
  
  # Map display with caching
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.5.1
  latlong2: ^0.9.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true